# Generated by Django 3.1.6 on 2022-02-10 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09123.....'. Up to 10 digits allowed.", regex='(0)+[0-9]{9}')], verbose_name='phone number'),
        ),
    ]
