# Generated by Django 3.1.6 on 2022-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220215_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.ManyToManyField(related_name='image_color', to='store.Color'),
        ),
    ]
